### ISSUE TITLE
tracking match rates by method

### ISSUE THREAD

**Issue by erikarasnick** [geomarker-io/parcel#12]
|parsing method    |  matching method | n unmatched addresses (>5 adm) | n unmatched admissions | n unmatched patients |
|:-------------------------------|:------|------:|------:|------:|
| `usaddress` | `csvlink` | 749 | 10,074 |  |
| `libpostal` | `hashdress` | 2,021 | 23,598 | |
| `libpostal` | `csvlink` | 2,020 | 23,567 | |
| `usaddress` | `hashdress` | 758 | 10,256 |  |

**Comment by erikarasnick** [comment]
My hypothesis about the postal parser being better looks to be incorrect. It seems like the success rate may actually have more to do with the parsing method than the matching method. Should we try tagging with `usaddress` and linking with the `hashdress` method?

**Comment by cole-brokamp** [comment]
yes, but would that require us to rewrite the postal container to only do expansion without parsing first?

**Comment by erikarasnick** [comment]
Oh, right, we have discussed that...

**Comment by cole-brokamp** [comment]
I think it's still probably worth a shot and separating them makes sense.  Do you want to fork `postal` again and just delete the part that does the address parsing?  Or you could start up the container and shell into it, in order to get just one run of the expansion without the parsing included.  If the performance is better, then we could invest more time into making a separate `expand` container based on libpostal.

**Comment by erikarasnick** [comment]
It looks like `usaddress` does better at parsing, and `csvlink` is doing slightly better at matching. Interesting how similar the matching methods perform when the parsing method is the same. I'm thinking the 750ish addresses that are remaining unmatched are mostly non-residential or problematic in some other way.  

I think based on this we can stick with `csvlink` and look into varying the `recall_weight`.

**Comment by erikarasnick** [comment]
Looking at the 749 addresses unmatched by `csvlink` and the 758 addresses unmatched by `hashdress`...

- 19 addresses are unmatched by `csvlink` but matched by the `hashdress` method. 

These are mostly street names that include cardinal directions (123 e main st) or are multiple words (123 ball park drive or 123 ballpark drive) 

- 28 addresses are unmatched by `hashdress` but matched by `csvlink`

These are mostly less common street suffixes (dr, blvd, ter, terr, pkwy, trail, ct), multi-word street names (some are a less common street suffix AND a multi-word street name), and a few are missing street name suffix
