### ISSUE TITLE
version differences in python packages

### ISSUE THREAD

**Issue by cole-brokamp** [geomarker-io/parcel#33]
I've seen this, but anecdotally have not seen any differences in tagging or linking results.  Could/should we:

- enforce versions of python packages?
- keep to inform users that want to install different versions themselves
- ignore and silence the message?

```
out <-
+     c("352 Helen St Cincinnati OH 45202",
+     "5377 Bahama Ter Cincinnati Ohio 45223",
+     "1851 Campbell Dr Hamilton Ohio 45011") |>
+     get_parcel_data()
/Users/cole/Library/r-miniconda-arm64/envs/r-reticulate/lib/python3.9/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.2.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/Users/cole/Library/r-miniconda-arm64/envs/r-reticulate/lib/python3.9/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator GridSearchCV from version 1.2.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

```

**Comment by cole-brokamp** [comment]
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations

could advise user to install older version of "pickle": `reticulate::py_install("pickle==1.2.2")`, but this didn't work for me.  It looks like `pickle` is included in python3.9, so might not be a good idea to try this.

how to write a better error message or warning message for this?

**Comment by cole-brokamp** [comment]
version of pickle likely determined by version of pandas

**Comment by cole-brokamp** [comment]
in new version of reticulate, use requirements file to create isolated virtualenv with required packages only to be used by the R package

**Comment by cole-brokamp** [comment]
I haven't seen this since I've been using virtualenv with a specific `r-parcel` environment

**Comment by cole-brokamp** [comment]
also much better with reticulate update and specifying python module versions in the R package DESCRIPTION file

**Comment by erikarasnick** [comment]
I was getting this error when running `get_parcel_data`:

```
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  dedupe.api.SettingsFileLoadingException: This settings file is not compatible with the current version of dedupe. This can happen if you have recently upgraded dedupe.
```

as well as this warning message 

```
/Users/RASV5G/Library/r-miniconda-arm64/lib/python3.10/site-packages/sklearn/base.py:376: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.3.0 when using version 1.4.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
```

I had to install `csvdedupe==0.1.20` *and* downgrade `scikit-learn` from version 1.4.2 to 1.3.0. Also note that installing `csvdedupe==0.1.20` installs `dedupe==1.10.0`, so `csvdedupe` should be installed first, then `dedupe==2.0.23`.
