### ISSUE TITLE
parcel id structure varies by data source

### ISSUE THREAD

**Issue by erikarasnick** [geomarker-io/parcel#52]
`cagis parcels` and `auditor online parcels`:  `0010001000400`
`cagis_parcel_id` from `cagis_addr` (used in `property_code_enforcements`: `000100010004`

I am fixing this for codec with:
```
  mutate(
    parcel_id = stringr::str_sub(cagis_parcel_id, 2), 
    parcel_id = stringr::str_pad(parcel_id, width = 13, side = "right", pad = "0"),
      .keep = "unused")
```

but there are ~10k parcels from `property_code_enforcements` that don't get matched to `cagis_parcels` when I left join.

**Comment by cole-brokamp** [comment]
The CAGIS addresses geodatabase has these different variations of identifiers and I might have chosen the wrong one here: https://github.com/cole-brokamp/addr/blob/a608771ceae6a9ddc3613bcffe7327a891e5ce28/data-raw/make_cagis_addr.R#L36  I think there is one called "AUDPTYID" or similar that might fix this issue.

**Comment by erikarasnick** [comment]
I don't see anything in the cagis quarterly addresses data that matches up. There is `PARCELID`, `GRPPCLID`, and `OLDPID` but I think they are all the same in most cases? 

Example: 

cagis_addr:
<img width="512" alt="Screenshot 2024-08-26 at 12 05 37 PM" src="https://github.com/user-attachments/assets/118d268d-35d9-4dcc-8238-6583a5b3a03d">

cagis_parcels:
<img width="492" alt="Screenshot 2024-08-26 at 12 05 51 PM" src="https://github.com/user-attachments/assets/35b94d24-86a9-4f54-a95d-6bc49b9d45cd">

**Comment by cole-brokamp** [comment]
OK, in that case probably a good idea to note in the overall README how to modify the parcel id to make sure anyone can merge them all.
