### ISSUE TITLE
clarifying "unmatched" versus "known non-residential" addresses

### ISSUE THREAD

**Issue by cole-brokamp** [geomarker-io/parcel#7]
Most of unmatched addresses are known non-residential addresses. If we created an input list of known non-residential addresses and matched them using csvlink, we could potentially be able to better estimate how many plausibly-residential addresses are could be missing.

**Comment by erikarasnick** [comment]
flag non-residential addresses 

- `222 e central pkwy`, `222 central pkwy` (JFS)
- `3031 eden ave`, `3010 eden ave` (Eden Ave apartments; temporary stays)
- `341 erkenbrecher ave`, `350 erkenbrecher ave` (Ronald McDonald House)
- `780 snider rd` (nursing home)
- `151 goodman dr` (Graduate Hotel)

**Comment by cole-brokamp** [comment]
add in these addresses at the step where we do the csv link using the address tags

**Comment by cole-brokamp** [comment]
https://github.com/degauss-org/dht/blob/4d10437461416e688ea259a37c2ce3b5bae96238/R/address_functions.R#L49-L77
