### ISSUE TITLE
`create_address_stub` should be an exported function

### ISSUE THREAD

**Issue by erikarasnick** [geomarker-io/parcel#8]
https://github.com/geomarker-io/parcel/blob/a19c012e826b63e1b4c1111eb76ac768ac4ff1a5/R/hashdress.R#L14

It is used in the csvdedupe script here: https://github.com/geomarker-io/parcel/blob/a19c012e826b63e1b4c1111eb76ac768ac4ff1a5/inst/csvlink_example.R#L16

and this code actually doesn't work without the `parcel:::` prefix currently.

**Comment by cole-brokamp** [comment]
yes, I think that is what I intended.  Can you do a PR to export it?
