### ISSUE TITLE
csvlink error in non-terminal R (e.g., RStudio, ESS)

### ISSUE THREAD

**Issue by erikarasnick** [geomarker-io/parcel#9]
When running the `csvlink` command using `system2` in rstudio, the interactive training process errors. The first question works, but when you give your response, it stalls. After escaping the command, I get this error. 

```
Traceback (most recent call last):
  File "/Users/RASV5G/Library/r-miniconda-arm64/envs/r-reticulate/bin/csvlink", line 8, in <module>
    sys.exit(launch_new_instance())
  File "/Users/RASV5G/Library/r-miniconda-arm64/envs/r-reticulate/lib/python3.8/site-packages/csvdedupe/csvlink.py", line 210, in launch_new_instance
    d.main()
  File "/Users/RASV5G/Library/r-miniconda-arm64/envs/r-reticulate/lib/python3.8/site-packages/csvdedupe/csvlink.py", line 137, in main
    self.dedupe_training(deduper)
  File "/Users/RASV5G/Library/r-miniconda-arm64/envs/r-reticulate/lib/python3.8/site-packages/csvdedupe/csvhelpers.py", line 262, in dedupe_training
    dedupe.consoleLabel(deduper)
  File "/Users/RASV5G/Library/r-miniconda-arm64/envs/r-reticulate/lib/python3.8/site-packages/dedupe/convenience.py", line 69, in consoleLabel
    user_input = input()
KeyboardInterrupt
```

**Comment by cole-brokamp** [comment]
It seems like maybe it isn't able to route the console input in R Studio back to the system process correctly.  Does it work if you run the exact same code from the exact same working directly outside of R Studio?

**Comment by erikarasnick** [comment]
I navigated to the same working directory and started R in the terminal. I had to redo the steps to install the python packages, but yes it worked in terminal outside of Rstudio

**Comment by cole-brokamp** [comment]
that's strange that it has to reinstall the python packages.  seems like it might not be using the same virtual environment?

**Comment by erikarasnick** [comment]
Yeah, I'm thinking I am using miniconda from rstudio and not from the terminal? Not sure...

**Comment by cole-brokamp** [comment]
try `reticulate::conda_list()` to view a list of the python environments it knows about

**Comment by cole-brokamp** [comment]
and `reticulate::miniconda_path()` to see which one of the environments it is set to use

**Comment by erikarasnick** [comment]
`reticulate::conda_list()`

```
          name                                                                              python
1 r-reticulate /Users/RASV5G/Desktop/riseup_geomarker_pipeline/renv/python/r-reticulate/bin/python
2         base                                  /Users/RASV5G/Library/r-miniconda-arm64/bin/python
3 r-reticulate                /Users/RASV5G/Library/r-miniconda-arm64/envs/r-reticulate/bin/python
```

`reticulate::miniconda_path()`

```
[1] "/Users/RASV5G/Library/r-miniconda-arm64"
```

I get the same thing in Rstudio and when running R from the terminal.

But if i quit R and restart R in terminal, I get `" "` for `Sys.which("csvlink")`

**Comment by cole-brokamp** [comment]
It looks like there are two conda environments with the same name -- one installed in library and one installed in the riseup_pipeline environment.  I would suggest manually deleting all of the "r-reticulate" and "r-miniconda" folders it is showing and start again from scratch in your home directory using terminal.  Using the install commands from reticulate in the README should install miniconda again if not available. Then start R studio and see if it can find the miniconda path.

**Comment by erikarasnick** [comment]
Thanks! I deleted both of those conda environments and reinstalled in my home directory, but I am still not able to get any response back from the console in Rstudio after answering the first training question.

**Comment by cole-brokamp** [comment]
I think it's definitely something with how the `system2` command receives input from the terminal.  I was actually running into problems with another version when running in emacs, but it would run fine in Terminal.  Could be related?  Everytime I ran it, it just core aborted R.

**Comment by cole-brokamp** [comment]
I didn't experience any issues using the dedupe python module via reticulate this most recent try.  Now that we don't have to use the prompt for training to match parcels to addresses, it doesn't seem so important to fix.

**Comment by cole-brokamp** [comment]
closing this for now...
